# Generated by Django 5.0.2 on 2024-02-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamescore_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='settings',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
