# Generated by Django 5.0.2 on 2024-02-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userscores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='settings',
            field=models.TextField(default='foo', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscore',
            name='type',
            field=models.TextField(default='math facts', max_length=100),
            preserve_default=False,
        ),
    ]
